### ISSUE TITLE
Error not raised for 400 status code

### ISSUE THREAD

**Issue by espen** [hintmedia/zoom_rb#388]
Looking at the code it seems like a 400 http status should [raise an error](https://github.com/hintmedia/zoom_rb/blob/master/lib/zoom/utils.rb#L21). I just get a 400 integer as a result when running a method.

```ruby
zoom_client.meeting_add_registrant(meeting_registrant_attributes)
=> 400
```

Shouldn't this raise an error? If not how can I rescue any errors from this lib?

**Comment by michaeldewolf85** [comment]
I ran into this in our installation as well. It seems that HttpParty has a 400 for the response code but this gem does not check the HttpParty `http_response.code` to determine the response code, instead it checks the code in the response body and Zoom is sending this:
```
{"code"=>200, "message"=>"No permission."}
```

**Steps to reproduce**
1. Create a valid Oauth token
2. Create a Zoom client
3. Call `zoom_client.meeting_list(user_id: 'notarealuserid')`

Observe that the http response code is 400 but Zoom sends a "code" attribute in the response of 200.

**Comment by michaeldewolf85** [comment]
The key to repro is to send a wrong user id even if the token is correct which gets zoom to send back a `400` bad request but oddly enough they send this body
```
{"code"=>200, "message"=>"No permission."}
```

**Comment by gerryster** [comment]
This seems like a wart in the Zoom API. However, it would be nice if this gem made the actual HTTP response code available. This could be done by adding the response code as an attribute of `Zoom::Error`.

**Comment by espen** [comment]
This is not ideal but a quick fix to trigger Zoom:Error for me: https://github.com/espen/zoom_rb/commit/d674dc1ce989263234a6b05fc4ae179c12fa00f1
