### ISSUE TITLE
Access token does not refresh

### ISSUE THREAD

**Issue by bonty** [hintmedia/zoom_rb#403]
Hello, thank you for great gem!

I found some token action does not work.
This might cause all actions using `request_headers` in [here](https://github.com/hintmedia/zoom_rb/blob/master/lib/zoom/actions.rb#L19).
I think token action must use `oauth_request_headers`.

Thank you.

**Comment by joelmichael** [comment]
Thanks, I am looking into this issue today.

**Comment by joelmichael** [comment]
Version 1.0.1 has been released to address this issue, can you please let me know if it resolved the problem?
