### ISSUE TITLE
require 'zoom'?

### ISSUE THREAD

**Issue by tarr11** [hintmedia/zoom_rb#41]
Not sure why, but I needed to use `require 'zoom'` and not `require 'zoom_rb'` as is specified in the docs

**Comment by kyleboe** [comment]
Hmmm looks like this is changed with #35. If you want to source from master for now. I'll get a new version of the gem published within a week.

**Comment by jgomo3** [comment]
So what can I expect when the new version is published?

I'm importing requiring 'zoom'. Should I be prepared to require 'zoom_rb' if I decide to use the latest version?

Also, I think there must be another workaround in the Rails world that doesn't require to change this library which was the reason for #35.

Maybe some mapping or setting giving an exception for how to autoload this library. You know, there are other things beside Rails in the Ruby world.

**Comment by manuel-arno-korfmann-webentwicklung** [comment]
Hey, is there some sort of mailing list where I could register to be notified once the new version is released?

**Comment by jgomo3** [comment]
> Hey, is there some sort of mailing list where I could register to be notified once the new version is released?

You can "Watch" this repository. There are many levels of "watching". One of those is "Release Only". That level or any other more detailed one should work for you.

**Comment by fatwong** [comment]
> Hmmm looks like this is changed with #35. If you want to source from master for now. I'll get a new version of the gem published within a week.

Any luck of getting a new version released?

**Comment by Bertg** [comment]
Asking the same question as above :)

**Comment by kyleboe** [comment]
This has been updated with the latest release of the gem https://github.com/hintmedia/zoom_rb/releases/tag/0.11.0

Thanks for getting that pushed out @joelmichael!
