### ISSUE TITLE
Is zoom_rb affected by recent CVEs?

### ISSUE THREAD

**Issue by rwoliver2** [hintmedia/zoom_rb#434]
There are quite a few CVEs lately against the Zoom client itself, and although the recent bulletin (https://explore.zoom.us/en/trust/security/security-bulletin/) stated that the web SDK was unaffected, I wanted to see if there are any known security issues with any of the earlier versions of this gem?

**Comment by kyleboe** [comment]
Hi @rwoliver2,

I appreciate the concern, but thankfully the lack of web SDK vulnerabilities applies to this project as well. This project is strictly a Ruby wrapper around the [Zoom API](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods). The platform-specific, native (Windows, Linux, macOS, etc) client SDK is where the announced vulnerabilities reside and this project (past and present) has zero overlap with those native libraries. 

To further clarify, we are using [JWT](https://github.com/hintmedia/zoom_rb/blob/main/lib/zoom/clients/jwt.rb) ([JWT spec](https://jwt.io/)) and/or [OAuth2](https://github.com/hintmedia/zoom_rb/blob/main/lib/zoom/clients/oauth.rb) ([OAuth2 Spec](https://oauth.net/2/)) for authentication/authorization so there are unlikely any issues with those battle-tested standards.

Thanks for the concern though :+1:
