### ISSUE TITLE
Access token recovery and response parsing broken?

### ISSUE THREAD

**Issue by Ulfmann** [hintmedia/zoom_rb#7]
When I try to retrieve a meeting list, I get the following output
```ruby
zoom_client.meeting_list(host_id: host_id)
=> {"code"=>124, "message"=>"Access token is required."}
```
I would have expected the client to do that for me. Well then, if I pass a brand-new token to this call, I get this
```ruby
zoom_client.meeting_list(host_id: host_id, access_token: zoom_client.access_token)
=> ArgumentError: comparison of String with 300 failed
from .../gems/zoom_rb-0.8.7/lib/zoom/utils.rb:15:in `>='
```
Okay, lets see what exactly is compared in _lib/zoom/utils.rb_
```ruby
def raise_if_error!(response)
  require 'pry'; binding.pry
  if response&.[]('code') && response['code'] >= 300
    # ...
pry(Zoom::Utils)> response['code']
=> "code"
```

Up to here I don't see a problem on my side. But since I still want to get my meeting list I had another look into the meeting_list method and executed the request manually
```ruby
pry(<Zoom::Client>)> self.class.post('/meeting/list', query: { host_id: host_id, access_token: access_token } )
=> #<HTTParty::Response:0x7fa90d406858 parsed_response= ...
```
So now I get my response. Could this be unexpected behaviour? Honestly, to me it even seems to be a serious bug since I can't use your Gem as it's supposed to be.

**Comment by shohey1226** [comment]
I pulled a fork made by @eclemens (https://github.com/eclemens/zoom_rb) and works fine.  I'm not sure he will merge his work on to here.

**Comment by kyleboe** [comment]
Got everything merged. You should be good to update to latest version of the gem (`0.9.1`)
